# Here is for CIFAR10:
model:
    image_size: 32
    out_channels: 3
    base_width: 128
    n_T: 100
    use_aug_label: False
    dropout: 0.15 # FM
    net_type: ncsnppedm
    average_loss: True # use average or sum for loss

    # sampler: euler
    # sampler: heun
    # sampler: edm
    # sampler: edm-sde
    # sampler: DDIM
    sampler: ban
    ode_solver: jax
    # ode_solver: scipy # rk45
    
    no_condition_t: False
    embedding_type: positional # FM
dataset:
    name: cifar10
    root: CIFAR # pytorch
    prefetch_factor: 2
    num_workers: 64 # NOTE: On V2, if you don't use num_workers=64, sometimes the code will exit unexpectedly
    cache: True
aug: 
    use_edm_aug: False # NOTE: if you want to turn on this, also turn on model.use_aug_label
fid:
    eval_only: False
    fid_per_epoch: 50
    num_samples: 50000
    cache_ref: /kmh-nfs-us-mount/data/cached/cifar10_jax_stats_20240820.npz # pytorch
evalu:
    ema: True
    sample: False
batch_size: 2048
num_epochs: 2000
learning_rate: 0.0008 # FM
lr_schedule: const
weight_decay: 0.0
optimizer: adamw
adam_b2: 0.95
grad_clip: 0.0
warmup_epochs: 200
log_per_step: 100
visualize_per_epoch: 50
eval_per_epoch: 80
checkpoint_per_epoch: 500
load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/sqa_Flow_matching/20241206_001843_i2wyhh_kmh-tpuvm-v3-32-1__b_lr_ep_eval/checkpoint_48000